-- DSMS 初始化 DDL（全量）
-- 说明：
-- 1) 在 PostgreSQL 执行
-- 2) 依赖 pgvector 扩展

CREATE EXTENSION IF NOT EXISTS vector;

-- 分类表
CREATE TABLE IF NOT EXISTS category (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL,
    parent_id INTEGER NULL REFERENCES category(id),
    category_type VARCHAR(20) NOT NULL DEFAULT 'system',
    scope VARCHAR(30) NOT NULL DEFAULT 'standard',
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_user VARCHAR(100) NOT NULL DEFAULT 'api',
    CONSTRAINT ck_category_type_valid CHECK (category_type IN ('system', 'custom')),
    CONSTRAINT ck_category_scope_valid CHECK (scope IN ('standard', 'metric', 'bizdict'))
);

CREATE INDEX IF NOT EXISTS ix_category_parent ON category (parent_id);
CREATE INDEX IF NOT EXISTS ix_category_scope ON category (scope);
CREATE INDEX IF NOT EXISTS ix_category_is_deleted ON category (is_deleted);
CREATE UNIQUE INDEX IF NOT EXISTS uq_category_name_parent_active
    ON category (name, COALESCE(parent_id, 0))
    WHERE is_deleted = FALSE;

-- 数据标准主表
CREATE TABLE IF NOT EXISTS datastandard (
    id UUID PRIMARY KEY,
    code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    description TEXT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    is_latest BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    category_id INTEGER NULL REFERENCES category(id),
    extattributes JSONB NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_user VARCHAR(100) NOT NULL DEFAULT 'api',
    CONSTRAINT ck_datastandard_version_positive CHECK (version >= 1),
    CONSTRAINT ck_datastandard_status_range CHECK (status >= 0 AND status <= 4)
);

CREATE INDEX IF NOT EXISTS ix_datastandard_code ON datastandard (code);
CREATE INDEX IF NOT EXISTS ix_datastandard_status ON datastandard (status);
CREATE INDEX IF NOT EXISTS ix_datastandard_latest ON datastandard (is_latest);
CREATE INDEX IF NOT EXISTS ix_datastandard_deleted ON datastandard (is_deleted);
CREATE INDEX IF NOT EXISTS ix_datastandard_category ON datastandard (category_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_datastandard_code_version_active
    ON datastandard (code, version)
    WHERE is_deleted = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_datastandard_code_published_active
    ON datastandard (code)
    WHERE is_deleted = FALSE AND status = 1 AND is_latest = TRUE;

-- 标准代码列表主表
CREATE TABLE IF NOT EXISTS standardcodelist (
    id UUID PRIMARY KEY,
    list_code VARCHAR(50) NOT NULL,
    name VARCHAR(200) NOT NULL,
    purpose TEXT NULL,
    status SMALLINT NOT NULL DEFAULT 0,
    version INTEGER NOT NULL DEFAULT 1,
    is_latest BOOLEAN NOT NULL DEFAULT FALSE,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_user VARCHAR(100) NOT NULL DEFAULT 'api',
    CONSTRAINT ck_standardcodelist_version_positive CHECK (version >= 1),
    CONSTRAINT ck_standardcodelist_status_range CHECK (status >= 0 AND status <= 4)
);

CREATE INDEX IF NOT EXISTS ix_standardcodelist_code ON standardcodelist (list_code);
CREATE INDEX IF NOT EXISTS ix_standardcodelist_status ON standardcodelist (status);
CREATE INDEX IF NOT EXISTS ix_standardcodelist_latest ON standardcodelist (is_latest);
CREATE INDEX IF NOT EXISTS ix_standardcodelist_deleted ON standardcodelist (is_deleted);
CREATE UNIQUE INDEX IF NOT EXISTS uq_standardcodelist_code_version_active
    ON standardcodelist (list_code, version)
    WHERE is_deleted = FALSE;
CREATE UNIQUE INDEX IF NOT EXISTS uq_standardcodelist_code_published_active
    ON standardcodelist (list_code)
    WHERE is_deleted = FALSE AND status = 1 AND is_latest = TRUE;

-- 标准代码子表
CREATE TABLE IF NOT EXISTS standardcodeitem (
    id UUID PRIMARY KEY,
    list_id UUID NOT NULL REFERENCES standardcodelist(id),
    item_code VARCHAR(100) NOT NULL,
    item_name VARCHAR(200) NOT NULL,
    meaning TEXT NULL,
    sort_order INTEGER NOT NULL DEFAULT 0,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_user VARCHAR(100) NOT NULL DEFAULT 'api'
);

CREATE INDEX IF NOT EXISTS ix_standardcodeitem_list_deleted ON standardcodeitem (list_id, is_deleted);
CREATE INDEX IF NOT EXISTS ix_standardcodeitem_name ON standardcodeitem (item_name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_standardcodeitem_list_code_active
    ON standardcodeitem (list_id, item_code)
    WHERE is_deleted = FALSE;

-- 数据标准与码表绑定关系
CREATE TABLE IF NOT EXISTS datastandardcodelink (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    standard_id UUID NOT NULL REFERENCES datastandard(id),
    code_list_id UUID NOT NULL REFERENCES standardcodelist(id),
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    last_update_user VARCHAR(100) NOT NULL DEFAULT 'api'
);

CREATE INDEX IF NOT EXISTS ix_datastandardcodelink_standard ON datastandardcodelink (standard_id);
CREATE INDEX IF NOT EXISTS ix_datastandardcodelink_codelist ON datastandardcodelink (code_list_id);
CREATE UNIQUE INDEX IF NOT EXISTS uq_datastandardcodelink_standard_active
    ON datastandardcodelink (standard_id)
    WHERE is_deleted = FALSE;

-- 多语言表
CREATE TABLE IF NOT EXISTS standardi18n (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refid UUID NOT NULL REFERENCES datastandard(id),
    fieldname VARCHAR(50) NOT NULL,
    language VARCHAR(10) NOT NULL,
    content TEXT NOT NULL,
    CONSTRAINT uq_standard_i18n_ref_field_lang UNIQUE (refid, fieldname, language)
);

CREATE INDEX IF NOT EXISTS ix_standard_i18n_ref_lang ON standardi18n (refid, language);

-- 向量存储表
CREATE TABLE IF NOT EXISTS standardvectorstore (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    refid UUID NOT NULL REFERENCES datastandard(id),
    lang VARCHAR(10) NOT NULL,
    modelname VARCHAR(100) NOT NULL,
    sourcecontent TEXT NOT NULL,
    embedding VECTOR(1024) NOT NULL,
    CONSTRAINT uq_std_vector_ref_lang_model UNIQUE (refid, lang, modelname)
);

CREATE INDEX IF NOT EXISTS ix_std_vector_ref_lang ON standardvectorstore (refid, lang);
CREATE INDEX IF NOT EXISTS idx_std_vector_hnsw
    ON standardvectorstore USING hnsw (embedding vector_cosine_ops)
    WITH (m = 16, ef_construction = 64);

-- 标准关系表
CREATE TABLE IF NOT EXISTS standardrelation (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sourceid VARCHAR(100) NOT NULL,
    sourcever VARCHAR(20) NULL,
    targetid VARCHAR(100) NOT NULL,
    targetver VARCHAR(20) NULL,
    reltype VARCHAR(30) NOT NULL,
    targettype VARCHAR(50) NOT NULL,
    relstatus INTEGER NOT NULL DEFAULT 0,
    CONSTRAINT uq_standardrelation_unique UNIQUE (sourceid, targetid, targetver, reltype, targettype)
);

CREATE INDEX IF NOT EXISTS ix_standardrelation_source ON standardrelation (sourceid);
CREATE INDEX IF NOT EXISTS ix_standardrelation_target ON standardrelation (targetid);
